FROM node:16.8.0-alpine3.11 as build-temp

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

RUN \
  npm install -g cnpm --registry=https://registry.npmmirror.com \
  && mkdir -p /build/packages/bi-common/ \
  && mkdir -p /build/packages/bi-manager/dist/ \
  && mkdir -p /build/packages/bi-manager-prod/ \
  && mkdir -p /build/packages/bi-manager-web/dist/ \
  && cnpm install -g node-prune \
  && cnpm i -g add node-gyp \
  # node-canvas
  # @see: https://github.com/Automattic/node-canvas/issues/1886#issuecomment-925928476
  && apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev python2 bash \
  && apk add --update libmount ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family fontconfig

WORKDIR /build

# Copy your packages
COPY packages/bi-manager/dist/ ./packages/bi-manager/dist/
COPY packages/bi-manager-web/dist/ ./packages/bi-manager-web/dist/

COPY packages/bi-manager/package.json packages/bi-manager/tsconfig.json /build/packages/bi-manager/
COPY packages/bi-common/package.json /build/packages/bi-common/
RUN cd /build/packages/bi-common/ && cnpm install

COPY packages/bi-common ./packages/bi-common/
RUN cd /build/packages/bi-common/ && npm run build && rm -rf node_modules

# 处理 bi-manager 的生产环境依赖
COPY packages/bi-manager/package.json /build/bi-manager-prod/

WORKDIR /build/bi-manager-prod
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true 
RUN cnpm install /build/packages/bi-common && cnpm install numeral sqlstring uuid && cnpm install --production && node-prune

# ===================
FROM alpine:latest
ENV TIME_ZONE=Asia/Shanghai
ENV NODE_ENV production
ENV PLATFORM X86

# https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine
RUN \
  mkdir -p /usr/src/app \
  mkdir -p /usr/src/app/view \
  mkdir -p /usr/src/app/dist \
  mkdir -p /usr/src/app/node_modules \
  && sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
  && echo "https://mirrors.aliyun.com/alpine/edge/community/" >> /etc/apk/repositories \
  && apk -U --no-cache update && apk add --no-cache --allow-untrusted nodejs yarn tzdata bash chromium nss ca-certificates font-wqy-zenhei \
  && rm -rf /var/cache/*

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /usr/src/app
# 拷贝 nodejs 服务
COPY --from=build-temp /build/packages/bi-manager/package.json /build/packages/bi-manager/tsconfig.json /usr/src/app/
COPY --from=build-temp /build/packages/bi-manager/dist/ /usr/src/app/dist/
COPY --from=build-temp /build/bi-manager-prod/node_modules/ /usr/src/app/node_modules/

# Copy Web production
COPY --from=build-temp /build/packages/bi-manager-web/dist/index.html /usr/src/app/view/
COPY --from=build-temp /build/packages/bi-manager-web/dist/ /usr/src/app/dist/app/public

EXPOSE 7001
CMD yarn run start:docker