/** 小组件类型 */
export enum ECOMPONENTTYPE {
  'TEXT' = 'TEXT',
  'DIVIDER' = 'DIVIDER',
  'TEXTDIVIDER' = 'TEXTDIVIDER',
  'RICHEDITOR' = 'RICHEDITOR',
  'TABS' = 'TABS',
  'TIME' = 'TIME',
  'MULTISOURCECARD' = 'MULTISOURCECARD',
  'BUILTIN_ACTIVEASSETS' = 'BUILTIN_ACTIVEASSETS',
  'BUILTIN_NEW_FOUNDED_ASSETS' = 'BUILTIN_NEW_FOUNDED_ASSETS',
  'ALARM' = 'ALARM'
}

export const COMPONENT_TYPE_LIST = [
  'TEXT',
  'DIVIDER',
  'TEXTDIVIDER',
  'RICHEDITOR',
  'TABS',
  'TIME',
  'MULTISOURCECARD',
  'BUILTIN_ACTIVEASSETS',
  'BUILTIN_NEW_FOUNDED_ASSETS',
  'ALARM'
];

export enum EBACKGROUNDTYPE {
  'EMPTY' = 'EMPTY',
  'GRID' ='GRID',
  'LINE' = 'LINE',
  'DEFAULT_PIC' = 'DEFAULT_PIC',
  'YELLOW_LEAVES' = 'YELLOW_LEAVES'
}

export const  BACKGROUND_TYPE_LABEL:Record<string,any> =  {
 [EBACKGROUNDTYPE.EMPTY]: '空白',
 [EBACKGROUNDTYPE.GRID]: '网格',
 [EBACKGROUNDTYPE.LINE]: '横线',
 [EBACKGROUNDTYPE.DEFAULT_PIC]: '默认图片',
 [EBACKGROUNDTYPE.YELLOW_LEAVES]: '枫叶🍁',
}
