/** 小组件类型 */
export enum ECOMPONENTTYPE {
  'TEXT' = 'TEXT',
  'DIVIDER' = 'DIVIDER',
  'TEXTDIVIDER' = 'TEXTDIVIDER',
  'RICHEDITOR' = 'RICHEDITOR',
  'TABS' = 'TABS',
  'TIME' = 'TIME',
  'MULTISOURCECARD' = 'MULTISOURCECARD',
  'BUILTIN_ACTIVEASSETS' = 'BUILTIN_ACTIVEASSETS',
  'BUILTIN_NEW_FOUNDED_ASSETS' = 'BUILTIN_NEW_FOUNDED_ASSETS',
  'ALARM' = 'ALARM'
}

export const COMPONENT_TYPE_LIST = [
  'TEXT',
  'DIVIDER',
  'TEXTDIVIDER',
  'RICHEDITOR',
  'TABS',
  'TIME',
  'MULTISOURCECARD',
  'BUILTIN_ACTIVEASSETS',
  'BUILTIN_NEW_FOUNDED_ASSETS',
  'ALARM'
];
